// Adapted from a roadmap the user found (ML Roadmap: Backend -> Applied ML), paraphrased and re-ordered for a beginner finishing Andrew Ng's course.
const SB = { label: "StatQuest (YouTube)", url: "https://www.youtube.com/@statquest" };

export const GATE = [
  "Both portfolio projects (CRUD API and Kitobon RAG) are live with links on your CV.",
  "Andrew Ng's Course 1 and 2 are finished, with the NumPy rewrites done.",
  "Your job search is running (5 applications a week). This list is for the job you land, not a reason to stop applying.",
];

export const PHASES = [
  {
    id: "A", name: "Evaluation rigor", weeks: "6–8 weeks",
    blurb: "Most ML failures are about measuring wrongly, not about the algorithm. This phase makes your numbers trustworthy.",
    topics: [
      { id: "a-split", kind: "must", title: "Train/validation/test and time-aware splits", hint: "the test set is touched once",
        why: "A score only means something if the data used to judge it never influenced the model.",
        learn: ["Roles of train, validation and test sets", "k-fold cross-validation", "Time-series splits: expanding window, so the model never sees the future"],
        fails: ["Random k-fold on time-ordered data scores beautifully and fails live", "Tuning on the test set, then reporting that score"],
        res: [SB], jump: { tab: "course", id: null, label: "Andrew Ng, Course 2 week 3" } },
      { id: "a-leak", kind: "must", title: "Data leakage", hint: "the #1 silent killer",
        why: "Leakage is the most common reason a model that looked great in testing dies after launch.",
        learn: ["Target leakage: a feature that contains the answer", "Preprocessing fitted on all data before splitting", "How to hunt it: suspiciously high scores, feature importance sanity check"],
        fails: ["An AUC of 0.99 is almost never real, find the leak", "Scaling or encoding before the split"], res: [] },
      { id: "a-metric", kind: "must", title: "Metrics that match the decision", hint: "accuracy lies",
        why: "Pick the metric from the cost of each kind of mistake, not from habit.",
        learn: ["Precision, recall, F1, ROC-AUC, PR-AUC and when each misleads", "Imbalanced data and thresholds", "Regression: MAE vs RMSE"],
        fails: ["99% accuracy on 1% positive data", "Optimizing a metric the business never asked for"], res: [SB] },
      { id: "a-feat", kind: "must", title: "Feature engineering", hint: "lags, rollings, encodings",
        why: "On tabular data, good features usually beat a fancier model.",
        learn: ["Lag and rolling-window features", "Categorical encodings and their leakage risks", "Missing values and scaling inside a pipeline"],
        fails: ["Features computed with future information", "Target encoding without out-of-fold"], res: [] },
      { id: "a-gbm", kind: "must", title: "Decision trees to LightGBM", hint: "understand it, then use it",
        why: "Gradient-boosted trees are the default winner on tabular data.",
        learn: ["How a tree splits (your From Scratch module)", "Boosting step by step", "Key LightGBM parameters and early stopping"],
        fails: ["Treating it as a black box and tuning blindly", "No early stopping, so it overfits"],
        res: [{ label: "LightGBM: parameters tuning", url: "https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html" }],
        jump: { tab: "scratch", id: "ensembles", label: "Ensemble Methods, From Scratch" } },
      { id: "a-calib", kind: "deep", title: "Probability calibration", hint: "when the output feeds a threshold",
        why: "A model that says 80% should be right about 80% of the time, or thresholds make bad decisions.",
        learn: ["Reliability curves", "Platt scaling and isotonic regression", "When calibration matters and when it does not"], fails: ["Using raw scores as probabilities"], res: [] },
      { id: "a-goal", kind: "goal", title: "Deliverable: honest evaluation harness", hint: "one real dataset, one table",
        why: "Proof you can measure honestly.",
        learn: ["Pick one real dataset", "Baseline first, then a model", "Correct split, right metric, one results table in the README"], fails: ["Reporting only the best run"], res: [] },
    ],
  },
  {
    id: "B", name: "Deep learning foundations", weeks: "5–6 weeks",
    blurb: "Build the deep learning mental model once, then stop and rely on libraries.",
    topics: [
      { id: "b-torch", kind: "must", title: "PyTorch and autograd", hint: "tensors, graphs, devices",
        why: "PyTorch reads like normal Python, and almost all modern work uses it.",
        learn: ["Tensors and shapes", "Autograd: how gradients are tracked", "CPU vs GPU devices"],
        fails: ["Shape mismatches", "Forgetting to zero gradients"],
        res: [{ label: "PyTorch: learn the basics", url: "https://pytorch.org/tutorials/beginner/basics/intro.html" }] },
      { id: "b-loop", kind: "must", title: "Write one training loop by hand", hint: "no wrappers, once",
        why: "It connects your NumPy backprop to real tooling.",
        learn: ["Forward, loss, backward, step", "Batches, epochs, validation each epoch", "Reading a loss curve"],
        fails: ["Loss goes NaN with no idea why", "Training on the validation set by mistake"],
        res: [{ label: "Karpathy: Zero to Hero", url: "https://karpathy.ai/zero-to-hero.html" }] },
      { id: "b-cnn", kind: "must", title: "CNNs and transfer learning", hint: "do not train from scratch",
        why: "Fine-tuning a pretrained model beats training your own for almost every small project.",
        learn: ["What convolutions detect", "Freeze, then fine-tune a pretrained backbone", "Data augmentation"],
        fails: ["Training from scratch on a tiny dataset"],
        res: [{ label: "fast.ai course", url: "https://course.fast.ai/" }] },
      { id: "b-attn", kind: "must", title: "Attention and the Transformer", hint: "build it once",
        why: "Every LLM you call is this architecture.",
        learn: ["Self-attention step by step", "Positional information", "Blocks stacked into a decoder"],
        fails: ["Memorizing diagrams without building it"],
        res: [{ label: "Karpathy: Zero to Hero", url: "https://karpathy.ai/zero-to-hero.html" }] },
      { id: "b-prac", kind: "deep", title: "Training practicalities", hint: "mixed precision, schedules, accumulation",
        why: "Makes training faster and fits bigger models in memory.",
        learn: ["Mixed precision", "Learning rate schedules and warmup", "Gradient accumulation"], fails: ["Changing five things at once"], res: [] },
      { id: "b-shift", kind: "must", title: "Distribution shift", hint: "97% in the notebook, 60% in the field",
        why: "Real data differs from your dataset, and that is where models fail.",
        learn: ["Why test data should look like production", "Collecting a small real-world check set", "Spotting shift early"], fails: ["Trusting a clean benchmark"], res: [] },
      { id: "b-goal", kind: "goal", title: "Deliverable: small classifier with a real-world test", hint: "image or text",
        why: "Shows transfer learning and honest evaluation together.",
        learn: ["Fine-tune a pretrained model", "Hold out photos or text from outside the training source", "Report both scores"], fails: ["Only reporting the easy test"], res: [] },
    ],
  },
  {
    id: "C", name: "Retrieval and RAG, deeper", weeks: "4–5 weeks",
    blurb: "You will already have a working RAG app. This phase makes it measurably better.",
    topics: [
      { id: "c-emb", kind: "must", title: "Tokenization and embeddings", hint: "what your RAG actually indexes",
        why: "Retrieval quality is limited by how text becomes vectors.",
        learn: ["Subword tokenization", "How embedding models are trained", "Dimension, cost and model choice"], fails: ["Treating embeddings as opaque arrays"],
        res: [], jump: { tab: "ledger", id: "sec-ragtheory", label: "RAG Theory: Embedding Chuqur" } },
      { id: "c-uz", kind: "must", title: "Embedding benchmark on your own language", hint: "a real gap and a real edge",
        why: "Public leaderboards are mostly English. A small Uzbek test set of your own is a differentiator.",
        learn: ["Build 50-100 question/answer pairs from real text", "Compare 2-3 embedding models on recall@k", "Record results in a table"], fails: ["Trusting a leaderboard instead of your data"],
        res: [{ label: "MTEB leaderboard", url: "https://huggingface.co/spaces/mteb/leaderboard" }] },
      { id: "c-eval", kind: "must", title: "RAG evaluation", hint: "most teams skip this",
        why: "Without a number you cannot tell if a change helped.",
        learn: ["Retrieval metrics: recall@k, MRR", "Answer quality: faithfulness and relevance", "Fixed eval set run on every change"], fails: ["Judging by three examples"],
        res: [{ label: "RAGAS docs", url: "https://docs.ragas.io" }], jump: { tab: "ledger", id: "sec-ragtheory", label: "RAG Evaluation (RAGAS)" } },
      { id: "c-hybrid", kind: "must", title: "Hybrid retrieval and reranking", hint: "BM25 + dense + cross-encoder",
        why: "Keyword and vector search fail in different ways. Combining them and reranking recovers most misses.",
        learn: ["BM25 keyword search", "Merging scores from two retrievers", "Cross-encoder reranking of the top results"], fails: ["Only dense search, missing exact terms and names"], res: [] },
      { id: "c-chunk", kind: "deep", title: "Chunking strategy", hint: "naive splitting destroys recall",
        why: "Chunk boundaries decide what the retriever can find.",
        learn: ["Sentence and paragraph boundaries", "Overlap", "Test chunk sizes with your eval set"], fails: ["Fixed character counts with no overlap"],
        res: [], jump: { tab: "ledger", id: "sec-ragtheory", label: "Chunking Strategiyalari" } },
      { id: "c-goal", kind: "goal", title: "Deliverable: RAG eval harness", hint: "nothing improves without a number",
        why: "One script that scores your pipeline and prints a table.",
        learn: ["Fixed question set", "Recall@k and an answer-quality score", "Before/after table for each change"], fails: ["Changing the eval set to fit the model"], res: [] },
    ],
  },
  {
    id: "D", name: "Fine-tuning and serving", weeks: "5–6 weeks",
    blurb: "When prompting is not enough, or an API costs too much.",
    topics: [
      { id: "d-enc", kind: "must", title: "Encoder fine-tuning", hint: "the right answer for classification",
        why: "A small fine-tuned encoder often beats prompting a large model on classification, cheaply.",
        learn: ["Fine-tuning a pretrained encoder", "Train/val/test with proper splits", "Compare against a prompt baseline"], fails: ["No baseline to beat"],
        res: [{ label: "Hugging Face: text classification", url: "https://huggingface.co/docs/transformers/tasks/sequence_classification" }] },
      { id: "d-sft", kind: "must", title: "Building an SFT dataset", hint: "80% of the work is here",
        why: "Fine-tuning quality is decided by the data.",
        learn: ["Instruction/response format", "Quality over quantity", "Held-out examples for evaluation"], fails: ["Noisy or duplicated examples"], res: [] },
      { id: "d-lora", kind: "must", title: "LoRA and QLoRA", hint: "rank, alpha, target modules",
        why: "Adapters let you tune a large model on one GPU.",
        learn: ["What low-rank adapters change", "Rank, alpha, target modules", "Quantization to save memory"], fails: ["Too high a rank, memorizing the data"],
        res: [{ label: "Hugging Face PEFT", url: "https://huggingface.co/docs/peft" }, { label: "Hugging Face TRL", url: "https://huggingface.co/docs/trl" }] },
      { id: "d-pref", kind: "deep", title: "Preference tuning: DPO / ORPO", hint: "the practical version of RLHF",
        why: "Shapes style and behavior using pairs of better/worse answers.",
        learn: ["Preference pair format", "DPO vs ORPO at a high level"], fails: ["Poor preference data"], res: [{ label: "TRL docs", url: "https://huggingface.co/docs/trl" }] },
      { id: "d-eval", kind: "must", title: "Fine-tune evaluation", hint: "does it beat base + prompt?",
        why: "If a prompted base model does as well, the fine-tune was wasted effort.",
        learn: ["Same eval set for base, prompted, fine-tuned", "Check regressions on general ability"], fails: ["Comparing against a weak baseline"], res: [] },
      { id: "d-serve", kind: "must", title: "vLLM, quantization and serving", hint: "latency, throughput, cost",
        why: "Serving cost and speed decide whether a model is usable.",
        learn: ["Serving with vLLM", "Quantization trade-offs", "Benchmark on your own hardware"], fails: ["Quoting numbers measured on someone else's machine"],
        res: [{ label: "vLLM docs", url: "https://docs.vllm.ai" }] },
      { id: "d-goal", kind: "goal", title: "Deliverable: local vs API cost report", hint: "real measured numbers",
        why: "A decision document with your own measurements.",
        learn: ["Same task on API and local model", "Quality, latency, cost per 1k requests", "A recommendation"], fails: ["Invented numbers"], res: [] },
    ],
  },
  {
    id: "E", name: "ML systems and MLOps", weeks: "4–6 weeks",
    blurb: "Keeping a model working after it ships. This builds on your backend skills.",
    topics: [
      { id: "e-track", kind: "must", title: "Experiment tracking and data versioning", hint: "MLflow, DVC",
        why: "You must be able to reproduce any past result.",
        learn: ["Log params, metrics and artifacts", "Version datasets", "Compare runs"], fails: ["Results nobody can reproduce"],
        res: [{ label: "MLflow docs", url: "https://mlflow.org/docs/latest/" }] },
      { id: "e-serve", kind: "must", title: "Model serving", hint: "FastAPI + ONNX",
        why: "A model is only useful behind a reliable API.",
        learn: ["Load once at startup", "Input validation", "Batching and timeouts"], fails: ["Loading the model per request"], res: [], jump: { tab: "scratch", id: "fastapi-basics", label: "FastAPI Fundamentals" } },
      { id: "e-skew", kind: "must", title: "Training/serving skew", hint: "the classic production failure",
        why: "Features computed differently in training and production quietly break accuracy.",
        learn: ["One shared feature code path", "Compare training and live feature stats"], fails: ["Re-implementing preprocessing in the API"], res: [] },
      { id: "e-drift", kind: "must", title: "Drift and monitoring", hint: "PSI, KS test, shadow deploys",
        why: "Data changes over time and accuracy decays without alarms.",
        learn: ["Population Stability Index and KS test", "Dashboards and alerts", "Shadow deployments"], fails: ["No monitoring until users complain"], res: [] },
      { id: "e-retrain", kind: "deep", title: "Retraining pipelines", hint: "automate last, not first",
        why: "Automate only after the manual process is stable.",
        learn: ["Scheduled vs triggered retraining", "Validation gate before promotion"], fails: ["Automating a broken process"], res: [] },
    ],
  },
];

export const SKIP = [
  "Kaggle grinding: it teaches overfitting to a leaderboard.",
  "Reading new papers daily: it feels productive and builds nothing.",
  "Rebuilding every model twice: once is education, twice is a hobby.",
  "Anything on this page before the January job search and portfolio are in place.",
];

export const LATER_TOTAL = PHASES.reduce((n, p) => n + p.topics.length, 0);
