export const PLAN_START = new Date("2026-10-01T00:00:00");

export const WEEKS = [
  {
    phase: "October",
    deliverable: "Python basics covered",
    why: "You already think like a backend developer — the risk isn't learning to program, it's PHP habits (loose typing, arrays-as-everything) slowing down Python's more explicit style.",
    how: [
      "Install Python 3.12 and always work inside a venv, never a global install",
      "Work through data types, control flow and functions in the official tutorial",
      "Write 2-3 small classes to get comfortable with __init__ and self",
      "Rewrite one existing PHP CLI script in plain Python",
    ],
    resources: [
      { label: "Python official tutorial", url: "https://docs.python.org/3/tutorial/" },
      { label: "Real Python: venv primer", url: "https://realpython.com/python-virtual-environments-a-primer/" },
    ],
    internal: [],
    jump: { tab: "scratch", id: "python-for-backend" },
  },
  {
    phase: "October",
    deliverable: "FastAPI + Postgres connected",
    why: "FastAPI is the standard framework for exactly the backend-plus-AI role you're targeting — closer to Laravel's explicitness than Django is.",
    how: [
      "Work through the official FastAPI tutorial end to end",
      "Connect to PostgreSQL with SQLAlchemy's quickstart",
      "Build one real GET + POST route validated with Pydantic, using Kitobon-shaped data, not filler",
    ],
    resources: [
      { label: "FastAPI tutorial", url: "https://fastapi.tiangolo.com/tutorial/" },
      { label: "SQLAlchemy 2.0 quickstart", url: "https://docs.sqlalchemy.org/en/20/orm/quickstart.html" },
      { label: "Pydantic docs", url: "https://docs.pydantic.dev/latest/" },
    ],
    internal: [],
    jump: { tab: "scratch", id: "fastapi-basics" },
  },
  {
    phase: "October",
    deliverable: "CRUD API pushed to GitHub",
    why: "The first shippable artifact — not a tutorial-along exercise, proof you can build in this stack unsupervised.",
    how: [
      "Pick one real resource, build full CRUD on it",
      "Use proper HTTP status codes — see the API Design rules in Pattern Manual",
      "Write a README someone else could actually follow",
      "Push to GitHub and deploy on any free tier",
    ],
    resources: [{ label: "Make a README", url: "https://www.makeareadme.com/" }],
    internal: [{ tab: "patterns", id: "api-design", label: "API Design rules — Pattern Manual" }],
    jump: { tab: "scratch", id: "crud-project" },
  },
  {
    phase: "October",
    deliverable: "LLM API calls working",
    why: "The module that turns 'backend developer' into 'backend developer who ships AI features' — the positioning the whole January target rests on.",
    how: [
      "Read Anthropic's API getting-started guide",
      "Call the API asking for structured JSON output, not free text",
      "Add streaming with FastAPI's StreamingResponse",
      "Validate every response against a Pydantic model before trusting it",
    ],
    resources: [
      { label: "Anthropic API: getting started", url: "https://docs.anthropic.com/en/api/getting-started" },
      { label: "Anthropic: streaming", url: "https://docs.anthropic.com/en/docs/build-with-claude/streaming" },
    ],
    internal: [],
    jump: { tab: "scratch", id: "llm-apis" },
  },
  {
    phase: "November",
    deliverable: "Kitobon AI feature v1 shipped",
    why: "Portfolio piece #1 — an AI feature shipped into a real, already-running product beats a toy demo every time in an interview.",
    how: [
      "Pick one small feature: a book summary or a recommendation line",
      "Wire it through last week's LLM call pattern",
      "Ship it behind a real Kitobon endpoint, not a local script",
    ],
    resources: [],
    internal: [{ tab: "scratch", id: "llm-apis", label: "Calling LLM APIs — From Scratch" }],
    jump: { tab: "scratch", id: "llm-apis" },
  },
  {
    phase: "November",
    deliverable: "pgvector search working",
    why: "Embeddings turn 'find similar things' into a math operation instead of a keyword match — the foundation everything RAG sits on.",
    how: [
      "Read pgvector's README",
      "Add a vector column to one real table",
      "Compute and store embeddings for real Kitobon rows",
      "Run a similarity query and sanity-check the results by eye",
    ],
    resources: [{ label: "pgvector (GitHub)", url: "https://github.com/pgvector/pgvector" }],
    internal: [{ tab: "ledger", id: "sec-ragtheory", label: "RAG Theory: Embedding Chuqur — Guide Index" }],
    jump: { tab: "scratch", id: "embeddings" },
  },
  {
    phase: "November",
    deliverable: "Chunking + retrieval pipeline",
    why: "Bad chunking is the single most common reason a RAG answer comes back wrong — get this step right before building anything downstream of it.",
    how: [
      "Read your own RAG Theory chapter on chunking before writing code",
      "Chunk on paragraph or sentence boundaries with overlap, never a fixed character count",
      "Build the embed-question → retrieve-chunks → assemble-prompt loop",
    ],
    resources: [],
    internal: [{ tab: "ledger", id: "sec-ragtheory", label: "Chunking Strategiyalari — Guide Index" }],
    jump: { tab: "scratch", id: "rag-pipeline" },
  },
  {
    phase: "November",
    deliverable: "RAG app served via FastAPI",
    why: "Portfolio piece #2, and the one that matters most for the January target.",
    how: [
      "Follow your own hands-on RAG build guide step by step, in order",
      "Use real Kitobon documents, never a toy dataset",
      "Serve it through a FastAPI endpoint the real app actually calls",
    ],
    resources: [],
    internal: [{ tab: "ledger", id: "sec-ragbuild", label: "Hands-On RAG Build (21 chapters) — Guide Index" }],
    jump: { tab: "scratch", id: "rag-project" },
  },
  {
    phase: "November",
    deliverable: "20-question eval run + fixes",
    why: "The 3 examples you tried while building are the ones you unconsciously designed the pipeline around — a real eval set catches what those 3 can't.",
    how: [
      "Write 20 real questions a user might actually ask",
      "Run each through the pipeline, mark pass or fail",
      "Fix the pattern behind each failure, not just that one case",
    ],
    resources: [],
    internal: [{ tab: "ledger", id: "sec-ragtheory", label: "RAG Evaluation — RAGAS — Guide Index" }],
    jump: { tab: "scratch", id: "rag-project-eval" },
  },
  {
    phase: "December",
    deliverable: "One project live via Docker",
    why: "A project that only runs on your laptop is a claim nobody can verify — a live URL is what an interviewer actually clicks.",
    how: [
      "Read Docker's official get-started guide",
      "Write a minimal Dockerfile for the FastAPI app",
      "Deploy both portfolio projects on any free tier (Render, Railway, Fly.io)",
    ],
    resources: [{ label: "Docker: get started", url: "https://docs.docker.com/get-started/" }],
    internal: [],
    jump: { tab: "scratch", id: "deployment" },
  },
  {
    phase: "December",
    deliverable: "CV + khayrullo.uz updated",
    why: "The work only counts if someone can find it and understand what it does for a user in ten seconds.",
    how: [
      "Lead with Laravel/PHP experience, then the Python + FastAPI + LLM/RAG projects",
      "Describe outcomes ('what it does for a user'), not just the tech stack",
      "Add live links to both projects, not just GitHub repos",
    ],
    resources: [],
    internal: [],
    jump: { tab: "scratch", id: "interview-prep-checklist" },
  },
  {
    phase: "December",
    deliverable: "Interview prep done",
    why: "Two strong projects mean nothing if you can't explain the decisions behind them under pressure.",
    how: [
      "Practice explaining, out loud: why pgvector over a dedicated vector DB, why you chunked the way you did",
      "Review gradient descent and overfitting from From Scratch",
      "Review the System Design basics from Pattern Manual",
    ],
    resources: [],
    internal: [
      { tab: "scratch", id: "linear-regression", label: "Linear Regression — From Scratch" },
      { tab: "patterns", id: "scaling-fundamentals", label: "System Design basics — Pattern Manual" },
    ],
    jump: { tab: "scratch", id: "interview-prep" },
  },
  {
    phase: "December",
    deliverable: "Caught up / extra applications",
    why: "Buffer week — if something slipped, this is where it gets absorbed instead of derailing the whole plan.",
    how: [
      "Finish whatever's still incomplete from weeks 1-12",
      "If nothing's incomplete, push past 5 applications this week",
    ],
    resources: [],
    internal: [],
    jump: null,
  },
];

export const ROADMAP_TOTAL = WEEKS.length * 13;
